// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package pg.tm470.boltfund.domain;

import javax.persistence.Entity;
import pg.tm470.boltfund.domain.Eat;

privileged aspect Eat_Roo_Jpa_Entity {
    
    declare @type: Eat: @Entity;
    
}
