// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package pg.tm470.boltfund.domain;

import org.springframework.beans.factory.annotation.Configurable;
import pg.tm470.boltfund.domain.Route;

privileged aspect Route_Roo_Configurable {
    
    declare @type: Route: @Configurable;
    
}
