// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package pg.tm470.boltfund.domain;

import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;
import pg.tm470.boltfund.domain.Bolter;
import pg.tm470.boltfund.domain.BolterDataOnDemand;
import pg.tm470.boltfund.domain.BolterIntegrationTest;

privileged aspect BolterIntegrationTest_Roo_IntegrationTest {
    
    declare @type: BolterIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: BolterIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: BolterIntegrationTest: @Transactional;
    
    @Autowired
    BolterDataOnDemand BolterIntegrationTest.dod;
    
    @Test
    public void BolterIntegrationTest.testCountBolters() {
        Assert.assertNotNull("Data on demand for 'Bolter' failed to initialize correctly", dod.getRandomBolter());
        long count = Bolter.countBolters();
        Assert.assertTrue("Counter for 'Bolter' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void BolterIntegrationTest.testFindBolter() {
        Bolter obj = dod.getRandomBolter();
        Assert.assertNotNull("Data on demand for 'Bolter' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Bolter' failed to provide an identifier", id);
        obj = Bolter.findBolter(id);
        Assert.assertNotNull("Find method for 'Bolter' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Bolter' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void BolterIntegrationTest.testFindAllBolters() {
        Assert.assertNotNull("Data on demand for 'Bolter' failed to initialize correctly", dod.getRandomBolter());
        long count = Bolter.countBolters();
        Assert.assertTrue("Too expensive to perform a find all test for 'Bolter', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Bolter> result = Bolter.findAllBolters();
        Assert.assertNotNull("Find all method for 'Bolter' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Bolter' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void BolterIntegrationTest.testFindBolterEntries() {
        Assert.assertNotNull("Data on demand for 'Bolter' failed to initialize correctly", dod.getRandomBolter());
        long count = Bolter.countBolters();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Bolter> result = Bolter.findBolterEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Bolter' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Bolter' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void BolterIntegrationTest.testFlush() {
        Bolter obj = dod.getRandomBolter();
        Assert.assertNotNull("Data on demand for 'Bolter' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Bolter' failed to provide an identifier", id);
        obj = Bolter.findBolter(id);
        Assert.assertNotNull("Find method for 'Bolter' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyBolter(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'Bolter' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void BolterIntegrationTest.testMergeUpdate() {
        Bolter obj = dod.getRandomBolter();
        Assert.assertNotNull("Data on demand for 'Bolter' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Bolter' failed to provide an identifier", id);
        obj = Bolter.findBolter(id);
        boolean modified =  dod.modifyBolter(obj);
        Integer currentVersion = obj.getVersion();
        Bolter merged = (Bolter)obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'Bolter' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void BolterIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'Bolter' failed to initialize correctly", dod.getRandomBolter());
        Bolter obj = dod.getNewTransientBolter(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Bolter' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Bolter' identifier to be null", obj.getId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'Bolter' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void BolterIntegrationTest.testRemove() {
        Bolter obj = dod.getRandomBolter();
        Assert.assertNotNull("Data on demand for 'Bolter' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Bolter' failed to provide an identifier", id);
        obj = Bolter.findBolter(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'Bolter' with identifier '" + id + "'", Bolter.findBolter(id));
    }
    
}
