// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package pg.tm470.boltfund.domain;

import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;
import pg.tm470.boltfund.domain.Crag;
import pg.tm470.boltfund.domain.CragDataOnDemand;
import pg.tm470.boltfund.domain.CragIntegrationTest;

privileged aspect CragIntegrationTest_Roo_IntegrationTest {
    
    declare @type: CragIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: CragIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: CragIntegrationTest: @Transactional;
    
    @Autowired
    CragDataOnDemand CragIntegrationTest.dod;
    
    @Test
    public void CragIntegrationTest.testCountCrags() {
        Assert.assertNotNull("Data on demand for 'Crag' failed to initialize correctly", dod.getRandomCrag());
        long count = Crag.countCrags();
        Assert.assertTrue("Counter for 'Crag' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void CragIntegrationTest.testFindCrag() {
        Crag obj = dod.getRandomCrag();
        Assert.assertNotNull("Data on demand for 'Crag' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Crag' failed to provide an identifier", id);
        obj = Crag.findCrag(id);
        Assert.assertNotNull("Find method for 'Crag' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Crag' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void CragIntegrationTest.testFindAllCrags() {
        Assert.assertNotNull("Data on demand for 'Crag' failed to initialize correctly", dod.getRandomCrag());
        long count = Crag.countCrags();
        Assert.assertTrue("Too expensive to perform a find all test for 'Crag', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Crag> result = Crag.findAllCrags();
        Assert.assertNotNull("Find all method for 'Crag' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Crag' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void CragIntegrationTest.testFindCragEntries() {
        Assert.assertNotNull("Data on demand for 'Crag' failed to initialize correctly", dod.getRandomCrag());
        long count = Crag.countCrags();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Crag> result = Crag.findCragEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Crag' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Crag' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void CragIntegrationTest.testFlush() {
        Crag obj = dod.getRandomCrag();
        Assert.assertNotNull("Data on demand for 'Crag' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Crag' failed to provide an identifier", id);
        obj = Crag.findCrag(id);
        Assert.assertNotNull("Find method for 'Crag' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyCrag(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'Crag' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void CragIntegrationTest.testMergeUpdate() {
        Crag obj = dod.getRandomCrag();
        Assert.assertNotNull("Data on demand for 'Crag' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Crag' failed to provide an identifier", id);
        obj = Crag.findCrag(id);
        boolean modified =  dod.modifyCrag(obj);
        Integer currentVersion = obj.getVersion();
        Crag merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'Crag' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void CragIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'Crag' failed to initialize correctly", dod.getRandomCrag());
        Crag obj = dod.getNewTransientCrag(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Crag' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Crag' identifier to be null", obj.getId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'Crag' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void CragIntegrationTest.testRemove() {
        Crag obj = dod.getRandomCrag();
        Assert.assertNotNull("Data on demand for 'Crag' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Crag' failed to provide an identifier", id);
        obj = Crag.findCrag(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'Crag' with identifier '" + id + "'", Crag.findCrag(id));
    }
    
}
