// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package pg.tm470.boltfund.domain;

import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;
import pg.tm470.boltfund.domain.Eat;
import pg.tm470.boltfund.domain.EatDataOnDemand;
import pg.tm470.boltfund.domain.EatIntegrationTest;

privileged aspect EatIntegrationTest_Roo_IntegrationTest {
    
    declare @type: EatIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: EatIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: EatIntegrationTest: @Transactional;
    
    @Autowired
    EatDataOnDemand EatIntegrationTest.dod;
    
    @Test
    public void EatIntegrationTest.testCountEats() {
        Assert.assertNotNull("Data on demand for 'Eat' failed to initialize correctly", dod.getRandomEat());
        long count = Eat.countEats();
        Assert.assertTrue("Counter for 'Eat' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void EatIntegrationTest.testFindEat() {
        Eat obj = dod.getRandomEat();
        Assert.assertNotNull("Data on demand for 'Eat' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Eat' failed to provide an identifier", id);
        obj = Eat.findEat(id);
        Assert.assertNotNull("Find method for 'Eat' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Eat' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void EatIntegrationTest.testFindAllEats() {
        Assert.assertNotNull("Data on demand for 'Eat' failed to initialize correctly", dod.getRandomEat());
        long count = Eat.countEats();
        Assert.assertTrue("Too expensive to perform a find all test for 'Eat', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Eat> result = Eat.findAllEats();
        Assert.assertNotNull("Find all method for 'Eat' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Eat' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void EatIntegrationTest.testFindEatEntries() {
        Assert.assertNotNull("Data on demand for 'Eat' failed to initialize correctly", dod.getRandomEat());
        long count = Eat.countEats();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Eat> result = Eat.findEatEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Eat' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Eat' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void EatIntegrationTest.testFlush() {
        Eat obj = dod.getRandomEat();
        Assert.assertNotNull("Data on demand for 'Eat' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Eat' failed to provide an identifier", id);
        obj = Eat.findEat(id);
        Assert.assertNotNull("Find method for 'Eat' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyEat(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'Eat' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void EatIntegrationTest.testMergeUpdate() {
        Eat obj = dod.getRandomEat();
        Assert.assertNotNull("Data on demand for 'Eat' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Eat' failed to provide an identifier", id);
        obj = Eat.findEat(id);
        boolean modified =  dod.modifyEat(obj);
        Integer currentVersion = obj.getVersion();
        Eat merged = (Eat)obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'Eat' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void EatIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'Eat' failed to initialize correctly", dod.getRandomEat());
        Eat obj = dod.getNewTransientEat(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Eat' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Eat' identifier to be null", obj.getId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'Eat' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void EatIntegrationTest.testRemove() {
        Eat obj = dod.getRandomEat();
        Assert.assertNotNull("Data on demand for 'Eat' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Eat' failed to provide an identifier", id);
        obj = Eat.findEat(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'Eat' with identifier '" + id + "'", Eat.findEat(id));
    }
    
}
