// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package pg.tm470.boltfund.domain;

import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.stereotype.Component;
import pg.tm470.boltfund.domain.Grade;
import pg.tm470.boltfund.domain.GradeDataOnDemand;

privileged aspect GradeDataOnDemand_Roo_DataOnDemand {
    
    declare @type: GradeDataOnDemand: @Component;
    
    private Random GradeDataOnDemand.rnd = new SecureRandom();
    
    private List<Grade> GradeDataOnDemand.data;
    
    public Grade GradeDataOnDemand.getNewTransientGrade(int index) {
        Grade obj = new Grade();
        setBrazilian(obj, index);
        setBritishAdj(obj, index);
        setBritishTec(obj, index);
        setEwbank(obj, index);
        setFinnish(obj, index);
        setFrench(obj, index);
        setNorwegian(obj, index);
        setSaxon(obj, index);
        setUiaa(obj, index);
        setYds(obj, index);
        return obj;
    }
    
    public void GradeDataOnDemand.setBrazilian(Grade obj, int index) {
        String brazilian = "bra_" + index;
        if (brazilian.length() > 5) {
            brazilian = brazilian.substring(0, 5);
        }
        obj.setBrazilian(brazilian);
    }
    
    public void GradeDataOnDemand.setBritishAdj(Grade obj, int index) {
        String britishAdj = "bri_" + index;
        if (britishAdj.length() > 5) {
            britishAdj = britishAdj.substring(0, 5);
        }
        obj.setBritishAdj(britishAdj);
    }
    
    public void GradeDataOnDemand.setBritishTec(Grade obj, int index) {
        String britishTec = "bri_" + index;
        if (britishTec.length() > 5) {
            britishTec = britishTec.substring(0, 5);
        }
        obj.setBritishTec(britishTec);
    }
    
    public void GradeDataOnDemand.setEwbank(Grade obj, int index) {
        String ewbank = "ewb_" + index;
        if (ewbank.length() > 5) {
            ewbank = ewbank.substring(0, 5);
        }
        obj.setEwbank(ewbank);
    }
    
    public void GradeDataOnDemand.setFinnish(Grade obj, int index) {
        String finnish = "fin_" + index;
        if (finnish.length() > 5) {
            finnish = finnish.substring(0, 5);
        }
        obj.setFinnish(finnish);
    }
    
    public void GradeDataOnDemand.setFrench(Grade obj, int index) {
        String french = "fre_" + index;
        if (french.length() > 5) {
            french = french.substring(0, 5);
        }
        obj.setFrench(french);
    }
    
    public void GradeDataOnDemand.setNorwegian(Grade obj, int index) {
        String norwegian = "nor_" + index;
        if (norwegian.length() > 5) {
            norwegian = norwegian.substring(0, 5);
        }
        obj.setNorwegian(norwegian);
    }
    
    public void GradeDataOnDemand.setSaxon(Grade obj, int index) {
        String saxon = "sax_" + index;
        if (saxon.length() > 5) {
            saxon = saxon.substring(0, 5);
        }
        obj.setSaxon(saxon);
    }
    
    public void GradeDataOnDemand.setUiaa(Grade obj, int index) {
        String uiaa = "uia_" + index;
        if (uiaa.length() > 5) {
            uiaa = uiaa.substring(0, 5);
        }
        obj.setUiaa(uiaa);
    }
    
    public void GradeDataOnDemand.setYds(Grade obj, int index) {
        String yds = "yds_" + index;
        if (yds.length() > 5) {
            yds = yds.substring(0, 5);
        }
        obj.setYds(yds);
    }
    
    public Grade GradeDataOnDemand.getSpecificGrade(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        Grade obj = data.get(index);
        Long id = obj.getId();
        return Grade.findGrade(id);
    }
    
    public Grade GradeDataOnDemand.getRandomGrade() {
        init();
        Grade obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return Grade.findGrade(id);
    }
    
    public boolean GradeDataOnDemand.modifyGrade(Grade obj) {
        return false;
    }
    
    public void GradeDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = Grade.findGradeEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'Grade' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<Grade>();
        for (int i = 0; i < 10; i++) {
            Grade obj = getNewTransientGrade(i);
            try {
                obj.persist();
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
