// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package pg.tm470.boltfund.domain;

import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;
import pg.tm470.boltfund.domain.PriceRange;
import pg.tm470.boltfund.domain.PriceRangeDataOnDemand;
import pg.tm470.boltfund.domain.PriceRangeIntegrationTest;

privileged aspect PriceRangeIntegrationTest_Roo_IntegrationTest {
    
    declare @type: PriceRangeIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: PriceRangeIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: PriceRangeIntegrationTest: @Transactional;
    
    @Autowired
    PriceRangeDataOnDemand PriceRangeIntegrationTest.dod;
    
    @Test
    public void PriceRangeIntegrationTest.testCountPriceRanges() {
        Assert.assertNotNull("Data on demand for 'PriceRange' failed to initialize correctly", dod.getRandomPriceRange());
        long count = PriceRange.countPriceRanges();
        Assert.assertTrue("Counter for 'PriceRange' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void PriceRangeIntegrationTest.testFindPriceRange() {
        PriceRange obj = dod.getRandomPriceRange();
        Assert.assertNotNull("Data on demand for 'PriceRange' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'PriceRange' failed to provide an identifier", id);
        obj = PriceRange.findPriceRange(id);
        Assert.assertNotNull("Find method for 'PriceRange' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'PriceRange' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void PriceRangeIntegrationTest.testFindAllPriceRanges() {
        Assert.assertNotNull("Data on demand for 'PriceRange' failed to initialize correctly", dod.getRandomPriceRange());
        long count = PriceRange.countPriceRanges();
        Assert.assertTrue("Too expensive to perform a find all test for 'PriceRange', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<PriceRange> result = PriceRange.findAllPriceRanges();
        Assert.assertNotNull("Find all method for 'PriceRange' illegally returned null", result);
        Assert.assertTrue("Find all method for 'PriceRange' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void PriceRangeIntegrationTest.testFindPriceRangeEntries() {
        Assert.assertNotNull("Data on demand for 'PriceRange' failed to initialize correctly", dod.getRandomPriceRange());
        long count = PriceRange.countPriceRanges();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<PriceRange> result = PriceRange.findPriceRangeEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'PriceRange' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'PriceRange' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void PriceRangeIntegrationTest.testFlush() {
        PriceRange obj = dod.getRandomPriceRange();
        Assert.assertNotNull("Data on demand for 'PriceRange' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'PriceRange' failed to provide an identifier", id);
        obj = PriceRange.findPriceRange(id);
        Assert.assertNotNull("Find method for 'PriceRange' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyPriceRange(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'PriceRange' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void PriceRangeIntegrationTest.testMergeUpdate() {
        PriceRange obj = dod.getRandomPriceRange();
        Assert.assertNotNull("Data on demand for 'PriceRange' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'PriceRange' failed to provide an identifier", id);
        obj = PriceRange.findPriceRange(id);
        boolean modified =  dod.modifyPriceRange(obj);
        Integer currentVersion = obj.getVersion();
        PriceRange merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'PriceRange' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void PriceRangeIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'PriceRange' failed to initialize correctly", dod.getRandomPriceRange());
        PriceRange obj = dod.getNewTransientPriceRange(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'PriceRange' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'PriceRange' identifier to be null", obj.getId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'PriceRange' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void PriceRangeIntegrationTest.testRemove() {
        PriceRange obj = dod.getRandomPriceRange();
        Assert.assertNotNull("Data on demand for 'PriceRange' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'PriceRange' failed to provide an identifier", id);
        obj = PriceRange.findPriceRange(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'PriceRange' with identifier '" + id + "'", PriceRange.findPriceRange(id));
    }
    
}
