// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package pg.tm470.boltfund.domain;

import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.stereotype.Component;
import pg.tm470.boltfund.domain.PriceRange;
import pg.tm470.boltfund.domain.PriceRangeDataOnDemand;

privileged aspect PriceRangeDataOnDemand_Roo_DataOnDemand {
    
    declare @type: PriceRangeDataOnDemand: @Component;
    
    private Random PriceRangeDataOnDemand.rnd = new SecureRandom();
    
    private List<PriceRange> PriceRangeDataOnDemand.data;
    
    public PriceRange PriceRangeDataOnDemand.getNewTransientPriceRange(int index) {
        PriceRange obj = new PriceRange();
        setName(obj, index);
        setPriceRange(obj, index);
        return obj;
    }
    
    public void PriceRangeDataOnDemand.setName(PriceRange obj, int index) {
        String name = "name_" + index;
        if (name.length() > 20) {
            name = name.substring(0, 20);
        }
        obj.setName(name);
    }
    
    public void PriceRangeDataOnDemand.setPriceRange(PriceRange obj, int index) {
        String priceRange = "priceRange_" + index;
        if (priceRange.length() > 30) {
            priceRange = priceRange.substring(0, 30);
        }
        obj.setPriceRange(priceRange);
    }
    
    public PriceRange PriceRangeDataOnDemand.getSpecificPriceRange(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        PriceRange obj = data.get(index);
        Long id = obj.getId();
        return PriceRange.findPriceRange(id);
    }
    
    public PriceRange PriceRangeDataOnDemand.getRandomPriceRange() {
        init();
        PriceRange obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return PriceRange.findPriceRange(id);
    }
    
    public boolean PriceRangeDataOnDemand.modifyPriceRange(PriceRange obj) {
        return false;
    }
    
    public void PriceRangeDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = PriceRange.findPriceRangeEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'PriceRange' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<PriceRange>();
        for (int i = 0; i < 10; i++) {
            PriceRange obj = getNewTransientPriceRange(i);
            try {
                obj.persist();
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
