// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package pg.tm470.boltfund.domain;

import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;
import pg.tm470.boltfund.domain.PrintedGuide;
import pg.tm470.boltfund.domain.PrintedGuideDataOnDemand;
import pg.tm470.boltfund.domain.PrintedGuideIntegrationTest;

privileged aspect PrintedGuideIntegrationTest_Roo_IntegrationTest {
    
    declare @type: PrintedGuideIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: PrintedGuideIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: PrintedGuideIntegrationTest: @Transactional;
    
    @Autowired
    PrintedGuideDataOnDemand PrintedGuideIntegrationTest.dod;
    
    @Test
    public void PrintedGuideIntegrationTest.testCountPrintedGuides() {
        Assert.assertNotNull("Data on demand for 'PrintedGuide' failed to initialize correctly", dod.getRandomPrintedGuide());
        long count = PrintedGuide.countPrintedGuides();
        Assert.assertTrue("Counter for 'PrintedGuide' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void PrintedGuideIntegrationTest.testFindPrintedGuide() {
        PrintedGuide obj = dod.getRandomPrintedGuide();
        Assert.assertNotNull("Data on demand for 'PrintedGuide' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'PrintedGuide' failed to provide an identifier", id);
        obj = PrintedGuide.findPrintedGuide(id);
        Assert.assertNotNull("Find method for 'PrintedGuide' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'PrintedGuide' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void PrintedGuideIntegrationTest.testFindAllPrintedGuides() {
        Assert.assertNotNull("Data on demand for 'PrintedGuide' failed to initialize correctly", dod.getRandomPrintedGuide());
        long count = PrintedGuide.countPrintedGuides();
        Assert.assertTrue("Too expensive to perform a find all test for 'PrintedGuide', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<PrintedGuide> result = PrintedGuide.findAllPrintedGuides();
        Assert.assertNotNull("Find all method for 'PrintedGuide' illegally returned null", result);
        Assert.assertTrue("Find all method for 'PrintedGuide' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void PrintedGuideIntegrationTest.testFindPrintedGuideEntries() {
        Assert.assertNotNull("Data on demand for 'PrintedGuide' failed to initialize correctly", dod.getRandomPrintedGuide());
        long count = PrintedGuide.countPrintedGuides();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<PrintedGuide> result = PrintedGuide.findPrintedGuideEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'PrintedGuide' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'PrintedGuide' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void PrintedGuideIntegrationTest.testFlush() {
        PrintedGuide obj = dod.getRandomPrintedGuide();
        Assert.assertNotNull("Data on demand for 'PrintedGuide' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'PrintedGuide' failed to provide an identifier", id);
        obj = PrintedGuide.findPrintedGuide(id);
        Assert.assertNotNull("Find method for 'PrintedGuide' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyPrintedGuide(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'PrintedGuide' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void PrintedGuideIntegrationTest.testMergeUpdate() {
        PrintedGuide obj = dod.getRandomPrintedGuide();
        Assert.assertNotNull("Data on demand for 'PrintedGuide' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'PrintedGuide' failed to provide an identifier", id);
        obj = PrintedGuide.findPrintedGuide(id);
        boolean modified =  dod.modifyPrintedGuide(obj);
        Integer currentVersion = obj.getVersion();
        PrintedGuide merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'PrintedGuide' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void PrintedGuideIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'PrintedGuide' failed to initialize correctly", dod.getRandomPrintedGuide());
        PrintedGuide obj = dod.getNewTransientPrintedGuide(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'PrintedGuide' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'PrintedGuide' identifier to be null", obj.getId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'PrintedGuide' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void PrintedGuideIntegrationTest.testRemove() {
        PrintedGuide obj = dod.getRandomPrintedGuide();
        Assert.assertNotNull("Data on demand for 'PrintedGuide' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'PrintedGuide' failed to provide an identifier", id);
        obj = PrintedGuide.findPrintedGuide(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'PrintedGuide' with identifier '" + id + "'", PrintedGuide.findPrintedGuide(id));
    }
    
}
