// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package pg.tm470.boltfund.domain;

import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.stereotype.Component;
import pg.tm470.boltfund.domain.Rating;
import pg.tm470.boltfund.domain.RatingDataOnDemand;

privileged aspect RatingDataOnDemand_Roo_DataOnDemand {
    
    declare @type: RatingDataOnDemand: @Component;
    
    private Random RatingDataOnDemand.rnd = new SecureRandom();
    
    private List<Rating> RatingDataOnDemand.data;
    
    public Rating RatingDataOnDemand.getNewTransientRating(int index) {
        Rating obj = new Rating();
        setDescription(obj, index);
        setName(obj, index);
        setScore(obj, index);
        return obj;
    }
    
    public void RatingDataOnDemand.setDescription(Rating obj, int index) {
        String description = "description_" + index;
        if (description.length() > 60) {
            description = description.substring(0, 60);
        }
        obj.setDescription(description);
    }
    
    public void RatingDataOnDemand.setName(Rating obj, int index) {
        String name = "name_" + index;
        if (name.length() > 20) {
            name = name.substring(0, 20);
        }
        obj.setName(name);
    }
    
    public void RatingDataOnDemand.setScore(Rating obj, int index) {
        Double score = new Integer(index).doubleValue();
        obj.setScore(score);
    }
    
    public Rating RatingDataOnDemand.getSpecificRating(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        Rating obj = data.get(index);
        Long id = obj.getId();
        return Rating.findRating(id);
    }
    
    public Rating RatingDataOnDemand.getRandomRating() {
        init();
        Rating obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return Rating.findRating(id);
    }
    
    public boolean RatingDataOnDemand.modifyRating(Rating obj) {
        return false;
    }
    
    public void RatingDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = Rating.findRatingEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'Rating' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<Rating>();
        for (int i = 0; i < 10; i++) {
            Rating obj = getNewTransientRating(i);
            try {
                obj.persist();
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
