// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package pg.tm470.boltfund.domain;

import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;
import pg.tm470.boltfund.domain.Route;
import pg.tm470.boltfund.domain.RouteDataOnDemand;
import pg.tm470.boltfund.domain.RouteIntegrationTest;

privileged aspect RouteIntegrationTest_Roo_IntegrationTest {
    
    declare @type: RouteIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: RouteIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: RouteIntegrationTest: @Transactional;
    
    @Autowired
    RouteDataOnDemand RouteIntegrationTest.dod;
    
    @Test
    public void RouteIntegrationTest.testCountRoutes() {
        Assert.assertNotNull("Data on demand for 'Route' failed to initialize correctly", dod.getRandomRoute());
        long count = Route.countRoutes();
        Assert.assertTrue("Counter for 'Route' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void RouteIntegrationTest.testFindRoute() {
        Route obj = dod.getRandomRoute();
        Assert.assertNotNull("Data on demand for 'Route' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Route' failed to provide an identifier", id);
        obj = Route.findRoute(id);
        Assert.assertNotNull("Find method for 'Route' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Route' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void RouteIntegrationTest.testFindAllRoutes() {
        Assert.assertNotNull("Data on demand for 'Route' failed to initialize correctly", dod.getRandomRoute());
        long count = Route.countRoutes();
        Assert.assertTrue("Too expensive to perform a find all test for 'Route', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Route> result = Route.findAllRoutes();
        Assert.assertNotNull("Find all method for 'Route' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Route' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void RouteIntegrationTest.testFindRouteEntries() {
        Assert.assertNotNull("Data on demand for 'Route' failed to initialize correctly", dod.getRandomRoute());
        long count = Route.countRoutes();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Route> result = Route.findRouteEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Route' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Route' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void RouteIntegrationTest.testFlush() {
        Route obj = dod.getRandomRoute();
        Assert.assertNotNull("Data on demand for 'Route' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Route' failed to provide an identifier", id);
        obj = Route.findRoute(id);
        Assert.assertNotNull("Find method for 'Route' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyRoute(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'Route' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void RouteIntegrationTest.testMergeUpdate() {
        Route obj = dod.getRandomRoute();
        Assert.assertNotNull("Data on demand for 'Route' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Route' failed to provide an identifier", id);
        obj = Route.findRoute(id);
        boolean modified =  dod.modifyRoute(obj);
        Integer currentVersion = obj.getVersion();
        Route merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'Route' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void RouteIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'Route' failed to initialize correctly", dod.getRandomRoute());
        Route obj = dod.getNewTransientRoute(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Route' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Route' identifier to be null", obj.getId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'Route' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void RouteIntegrationTest.testRemove() {
        Route obj = dod.getRandomRoute();
        Assert.assertNotNull("Data on demand for 'Route' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Route' failed to provide an identifier", id);
        obj = Route.findRoute(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'Route' with identifier '" + id + "'", Route.findRoute(id));
    }
    
}
