// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package pg.tm470.boltfund.domain;

import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;
import pg.tm470.boltfund.domain.CragDataOnDemand;
import pg.tm470.boltfund.domain.Sector;
import pg.tm470.boltfund.domain.SectorDataOnDemand;

privileged aspect SectorDataOnDemand_Roo_DataOnDemand {
    
    declare @type: SectorDataOnDemand: @Component;
    
    private Random SectorDataOnDemand.rnd = new SecureRandom();
    
    private List<Sector> SectorDataOnDemand.data;
    
    @Autowired
    CragDataOnDemand SectorDataOnDemand.cragDataOnDemand;
    
    public Sector SectorDataOnDemand.getNewTransientSector(int index) {
        Sector obj = new Sector();
        setAccess(obj, index);
        setDescription(obj, index);
        setName(obj, index);
        setNotes(obj, index);
        return obj;
    }
    
    public void SectorDataOnDemand.setAccess(Sector obj, int index) {
        String access = "access_" + index;
        if (access.length() > 5000) {
            access = access.substring(0, 5000);
        }
        obj.setAccess(access);
    }
    
    public void SectorDataOnDemand.setDescription(Sector obj, int index) {
        String description = "description_" + index;
        if (description.length() > 5000) {
            description = description.substring(0, 5000);
        }
        obj.setDescription(description);
    }
    
    public void SectorDataOnDemand.setName(Sector obj, int index) {
        String name = "name_" + index;
        if (name.length() > 20) {
            name = name.substring(0, 20);
        }
        obj.setName(name);
    }
    
    public void SectorDataOnDemand.setNotes(Sector obj, int index) {
        String notes = "notes_" + index;
        if (notes.length() > 2000) {
            notes = notes.substring(0, 2000);
        }
        obj.setNotes(notes);
    }
    
    public Sector SectorDataOnDemand.getSpecificSector(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        Sector obj = data.get(index);
        Long id = obj.getId();
        return Sector.findSector(id);
    }
    
    public Sector SectorDataOnDemand.getRandomSector() {
        init();
        Sector obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return Sector.findSector(id);
    }
    
    public boolean SectorDataOnDemand.modifySector(Sector obj) {
        return false;
    }
    
    public void SectorDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = Sector.findSectorEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'Sector' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<Sector>();
        for (int i = 0; i < 10; i++) {
            Sector obj = getNewTransientSector(i);
            try {
                obj.persist();
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
