// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package pg.tm470.boltfund.domain;

import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;
import pg.tm470.boltfund.domain.Shop;
import pg.tm470.boltfund.domain.ShopDataOnDemand;
import pg.tm470.boltfund.domain.ShopIntegrationTest;

privileged aspect ShopIntegrationTest_Roo_IntegrationTest {
    
    declare @type: ShopIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: ShopIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: ShopIntegrationTest: @Transactional;
    
    @Autowired
    ShopDataOnDemand ShopIntegrationTest.dod;
    
    @Test
    public void ShopIntegrationTest.testCountShops() {
        Assert.assertNotNull("Data on demand for 'Shop' failed to initialize correctly", dod.getRandomShop());
        long count = Shop.countShops();
        Assert.assertTrue("Counter for 'Shop' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void ShopIntegrationTest.testFindShop() {
        Shop obj = dod.getRandomShop();
        Assert.assertNotNull("Data on demand for 'Shop' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Shop' failed to provide an identifier", id);
        obj = Shop.findShop(id);
        Assert.assertNotNull("Find method for 'Shop' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Shop' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void ShopIntegrationTest.testFindAllShops() {
        Assert.assertNotNull("Data on demand for 'Shop' failed to initialize correctly", dod.getRandomShop());
        long count = Shop.countShops();
        Assert.assertTrue("Too expensive to perform a find all test for 'Shop', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Shop> result = Shop.findAllShops();
        Assert.assertNotNull("Find all method for 'Shop' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Shop' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void ShopIntegrationTest.testFindShopEntries() {
        Assert.assertNotNull("Data on demand for 'Shop' failed to initialize correctly", dod.getRandomShop());
        long count = Shop.countShops();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Shop> result = Shop.findShopEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Shop' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Shop' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void ShopIntegrationTest.testFlush() {
        Shop obj = dod.getRandomShop();
        Assert.assertNotNull("Data on demand for 'Shop' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Shop' failed to provide an identifier", id);
        obj = Shop.findShop(id);
        Assert.assertNotNull("Find method for 'Shop' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyShop(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'Shop' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void ShopIntegrationTest.testMergeUpdate() {
        Shop obj = dod.getRandomShop();
        Assert.assertNotNull("Data on demand for 'Shop' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Shop' failed to provide an identifier", id);
        obj = Shop.findShop(id);
        boolean modified =  dod.modifyShop(obj);
        Integer currentVersion = obj.getVersion();
        Shop merged = (Shop)obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'Shop' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void ShopIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'Shop' failed to initialize correctly", dod.getRandomShop());
        Shop obj = dod.getNewTransientShop(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Shop' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Shop' identifier to be null", obj.getId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'Shop' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void ShopIntegrationTest.testRemove() {
        Shop obj = dod.getRandomShop();
        Assert.assertNotNull("Data on demand for 'Shop' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Shop' failed to provide an identifier", id);
        obj = Shop.findShop(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'Shop' with identifier '" + id + "'", Shop.findShop(id));
    }
    
}
