// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package pg.tm470.boltfund.domain;

import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;
import pg.tm470.boltfund.domain.Sleep;
import pg.tm470.boltfund.domain.SleepDataOnDemand;
import pg.tm470.boltfund.domain.SleepIntegrationTest;

privileged aspect SleepIntegrationTest_Roo_IntegrationTest {
    
    declare @type: SleepIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: SleepIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: SleepIntegrationTest: @Transactional;
    
    @Autowired
    SleepDataOnDemand SleepIntegrationTest.dod;
    
    @Test
    public void SleepIntegrationTest.testCountSleeps() {
        Assert.assertNotNull("Data on demand for 'Sleep' failed to initialize correctly", dod.getRandomSleep());
        long count = Sleep.countSleeps();
        Assert.assertTrue("Counter for 'Sleep' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void SleepIntegrationTest.testFindSleep() {
        Sleep obj = dod.getRandomSleep();
        Assert.assertNotNull("Data on demand for 'Sleep' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Sleep' failed to provide an identifier", id);
        obj = Sleep.findSleep(id);
        Assert.assertNotNull("Find method for 'Sleep' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Sleep' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void SleepIntegrationTest.testFindAllSleeps() {
        Assert.assertNotNull("Data on demand for 'Sleep' failed to initialize correctly", dod.getRandomSleep());
        long count = Sleep.countSleeps();
        Assert.assertTrue("Too expensive to perform a find all test for 'Sleep', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Sleep> result = Sleep.findAllSleeps();
        Assert.assertNotNull("Find all method for 'Sleep' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Sleep' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void SleepIntegrationTest.testFindSleepEntries() {
        Assert.assertNotNull("Data on demand for 'Sleep' failed to initialize correctly", dod.getRandomSleep());
        long count = Sleep.countSleeps();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Sleep> result = Sleep.findSleepEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Sleep' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Sleep' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void SleepIntegrationTest.testFlush() {
        Sleep obj = dod.getRandomSleep();
        Assert.assertNotNull("Data on demand for 'Sleep' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Sleep' failed to provide an identifier", id);
        obj = Sleep.findSleep(id);
        Assert.assertNotNull("Find method for 'Sleep' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifySleep(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'Sleep' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void SleepIntegrationTest.testMergeUpdate() {
        Sleep obj = dod.getRandomSleep();
        Assert.assertNotNull("Data on demand for 'Sleep' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Sleep' failed to provide an identifier", id);
        obj = Sleep.findSleep(id);
        boolean modified =  dod.modifySleep(obj);
        Integer currentVersion = obj.getVersion();
        Sleep merged = (Sleep)obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'Sleep' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void SleepIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'Sleep' failed to initialize correctly", dod.getRandomSleep());
        Sleep obj = dod.getNewTransientSleep(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Sleep' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Sleep' identifier to be null", obj.getId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'Sleep' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void SleepIntegrationTest.testRemove() {
        Sleep obj = dod.getRandomSleep();
        Assert.assertNotNull("Data on demand for 'Sleep' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Sleep' failed to provide an identifier", id);
        obj = Sleep.findSleep(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'Sleep' with identifier '" + id + "'", Sleep.findSleep(id));
    }
    
}
