// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package pg.tm470.boltfund.domain;

import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.stereotype.Component;
import pg.tm470.boltfund.domain.Style;
import pg.tm470.boltfund.domain.StyleDataOnDemand;

privileged aspect StyleDataOnDemand_Roo_DataOnDemand {
    
    declare @type: StyleDataOnDemand: @Component;
    
    private Random StyleDataOnDemand.rnd = new SecureRandom();
    
    private List<Style> StyleDataOnDemand.data;
    
    public Style StyleDataOnDemand.getNewTransientStyle(int index) {
        Style obj = new Style();
        setDescription(obj, index);
        setName(obj, index);
        return obj;
    }
    
    public void StyleDataOnDemand.setDescription(Style obj, int index) {
        String description = "description_" + index;
        if (description.length() > 60) {
            description = description.substring(0, 60);
        }
        obj.setDescription(description);
    }
    
    public void StyleDataOnDemand.setName(Style obj, int index) {
        String name = "name_" + index;
        if (name.length() > 20) {
            name = name.substring(0, 20);
        }
        obj.setName(name);
    }
    
    public Style StyleDataOnDemand.getSpecificStyle(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        Style obj = data.get(index);
        Long id = obj.getId();
        return Style.findStyle(id);
    }
    
    public Style StyleDataOnDemand.getRandomStyle() {
        init();
        Style obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return Style.findStyle(id);
    }
    
    public boolean StyleDataOnDemand.modifyStyle(Style obj) {
        return false;
    }
    
    public void StyleDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = Style.findStyleEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'Style' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<Style>();
        for (int i = 0; i < 10; i++) {
            Style obj = getNewTransientStyle(i);
            try {
                obj.persist();
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
