// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package pg.tm470.boltfund.domain;

import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;
import pg.tm470.boltfund.domain.Style;
import pg.tm470.boltfund.domain.StyleDataOnDemand;
import pg.tm470.boltfund.domain.StyleIntegrationTest;

privileged aspect StyleIntegrationTest_Roo_IntegrationTest {
    
    declare @type: StyleIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: StyleIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: StyleIntegrationTest: @Transactional;
    
    @Autowired
    StyleDataOnDemand StyleIntegrationTest.dod;
    
    @Test
    public void StyleIntegrationTest.testCountStyles() {
        Assert.assertNotNull("Data on demand for 'Style' failed to initialize correctly", dod.getRandomStyle());
        long count = Style.countStyles();
        Assert.assertTrue("Counter for 'Style' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void StyleIntegrationTest.testFindStyle() {
        Style obj = dod.getRandomStyle();
        Assert.assertNotNull("Data on demand for 'Style' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Style' failed to provide an identifier", id);
        obj = Style.findStyle(id);
        Assert.assertNotNull("Find method for 'Style' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Style' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void StyleIntegrationTest.testFindAllStyles() {
        Assert.assertNotNull("Data on demand for 'Style' failed to initialize correctly", dod.getRandomStyle());
        long count = Style.countStyles();
        Assert.assertTrue("Too expensive to perform a find all test for 'Style', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Style> result = Style.findAllStyles();
        Assert.assertNotNull("Find all method for 'Style' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Style' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void StyleIntegrationTest.testFindStyleEntries() {
        Assert.assertNotNull("Data on demand for 'Style' failed to initialize correctly", dod.getRandomStyle());
        long count = Style.countStyles();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Style> result = Style.findStyleEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Style' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Style' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void StyleIntegrationTest.testFlush() {
        Style obj = dod.getRandomStyle();
        Assert.assertNotNull("Data on demand for 'Style' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Style' failed to provide an identifier", id);
        obj = Style.findStyle(id);
        Assert.assertNotNull("Find method for 'Style' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyStyle(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'Style' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void StyleIntegrationTest.testMergeUpdate() {
        Style obj = dod.getRandomStyle();
        Assert.assertNotNull("Data on demand for 'Style' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Style' failed to provide an identifier", id);
        obj = Style.findStyle(id);
        boolean modified =  dod.modifyStyle(obj);
        Integer currentVersion = obj.getVersion();
        Style merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'Style' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void StyleIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'Style' failed to initialize correctly", dod.getRandomStyle());
        Style obj = dod.getNewTransientStyle(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Style' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Style' identifier to be null", obj.getId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'Style' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void StyleIntegrationTest.testRemove() {
        Style obj = dod.getRandomStyle();
        Assert.assertNotNull("Data on demand for 'Style' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Style' failed to provide an identifier", id);
        obj = Style.findStyle(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'Style' with identifier '" + id + "'", Style.findStyle(id));
    }
    
}
