// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package pg.tm470.boltfund.domain;

import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;
import pg.tm470.boltfund.domain.WebUser;
import pg.tm470.boltfund.domain.WebUserDataOnDemand;
import pg.tm470.boltfund.domain.WebUserIntegrationTest;

privileged aspect WebUserIntegrationTest_Roo_IntegrationTest {
    
    declare @type: WebUserIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: WebUserIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: WebUserIntegrationTest: @Transactional;
    
    @Autowired
    WebUserDataOnDemand WebUserIntegrationTest.dod;
    
    @Test
    public void WebUserIntegrationTest.testCountWebUsers() {
        Assert.assertNotNull("Data on demand for 'WebUser' failed to initialize correctly", dod.getRandomWebUser());
        long count = WebUser.countWebUsers();
        Assert.assertTrue("Counter for 'WebUser' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void WebUserIntegrationTest.testFindWebUser() {
        WebUser obj = dod.getRandomWebUser();
        Assert.assertNotNull("Data on demand for 'WebUser' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'WebUser' failed to provide an identifier", id);
        obj = WebUser.findWebUser(id);
        Assert.assertNotNull("Find method for 'WebUser' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'WebUser' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void WebUserIntegrationTest.testFindAllWebUsers() {
        Assert.assertNotNull("Data on demand for 'WebUser' failed to initialize correctly", dod.getRandomWebUser());
        long count = WebUser.countWebUsers();
        Assert.assertTrue("Too expensive to perform a find all test for 'WebUser', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<WebUser> result = WebUser.findAllWebUsers();
        Assert.assertNotNull("Find all method for 'WebUser' illegally returned null", result);
        Assert.assertTrue("Find all method for 'WebUser' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void WebUserIntegrationTest.testFindWebUserEntries() {
        Assert.assertNotNull("Data on demand for 'WebUser' failed to initialize correctly", dod.getRandomWebUser());
        long count = WebUser.countWebUsers();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<WebUser> result = WebUser.findWebUserEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'WebUser' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'WebUser' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void WebUserIntegrationTest.testFlush() {
        WebUser obj = dod.getRandomWebUser();
        Assert.assertNotNull("Data on demand for 'WebUser' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'WebUser' failed to provide an identifier", id);
        obj = WebUser.findWebUser(id);
        Assert.assertNotNull("Find method for 'WebUser' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyWebUser(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'WebUser' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void WebUserIntegrationTest.testMergeUpdate() {
        WebUser obj = dod.getRandomWebUser();
        Assert.assertNotNull("Data on demand for 'WebUser' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'WebUser' failed to provide an identifier", id);
        obj = WebUser.findWebUser(id);
        boolean modified =  dod.modifyWebUser(obj);
        Integer currentVersion = obj.getVersion();
        WebUser merged = (WebUser)obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'WebUser' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void WebUserIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'WebUser' failed to initialize correctly", dod.getRandomWebUser());
        WebUser obj = dod.getNewTransientWebUser(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'WebUser' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'WebUser' identifier to be null", obj.getId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'WebUser' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void WebUserIntegrationTest.testRemove() {
        WebUser obj = dod.getRandomWebUser();
        Assert.assertNotNull("Data on demand for 'WebUser' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'WebUser' failed to provide an identifier", id);
        obj = WebUser.findWebUser(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'WebUser' with identifier '" + id + "'", WebUser.findWebUser(id));
    }
    
}
